/* :ts=4                        cp4_locstrs.c
 *
 *    cp4 - Commodore C+4 emulator
 *    Copyright (C) 1998 Gáti Gergely
 *
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 2 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software Foundation,
 *    Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *    e-mail: gatig@dragon.klte.hu
 */

static char *cp4_DefaultStrings[]={
    "***ERROR",
    "Error at aim calculating",
    "Plus/4 Crashed",
    "Wrong data sizes for emulation.\nRecompile the package!\n",
    "Can't open intuition",
    "Not enough memory\n",
    "Copyright (C) 1998 Gáti Gergely\nThis program is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation.\n\n",
    "Basic ROM not found",
    "Kernal ROM not found",
    "Save memory",
    "Debug",
    " - Illegal opcode",
    " - C+4 crashed",
    " - at BreakPoint %d",
    "cp4 System monitor",
    "Project",
    "Prefs...",
    "Save mem...",
    "W",
    "Reset",
    "Back",
    "B",
    "Quit",
    "Trace",
    "T",
    "Step",
    "S",
    "Run",
    "R",
    "??? With Data",
    "BreakPoints",
    "P",
    "Illegal OpCodes",
    "I",
    "Stack...",
    "K",
    "Monitor",
    "OpenWin...",
    "M",
    "Follow",
    "F",
    "Ascii",
    "A",
    "ScreenCode",
    "C",
    "_Run",
    "_Trace",
    "_Step",
    "Clear",
    "Add",
    "Amiga raster",
    "C+4 raster",
    "Video matrix",
    "Gfx base",
    "Raster request",
    "Ras/C#1/C#2/C#3",
    "Search",
    "Stack",
    "Save Mem",
    "From",
    "To",
    "Save",
    "Cancel",
    "Open",
    "Exit",
    "New",
    "Functions",
    "cp4 Keymap",
    "Assign key to '",
    "Assigned key(s)",
    "Pressed key",
    "Replace",
    "Assigned key",
    "Assign",
    "Ok",
    "Percent",
    "HardReset",
    "Load File",
    "Prefs",
    "Limit",
    "Swap Joy",
    "User Blank",
    "Joy Up",
    "Joy Down",
    "Joy Left",
    "Joy Right",
    "Joy U-L",
    "Joy U-R",
    "Joy D-L",
    "Joy D-R",
    "Joy Fire",
    "Function keys",
    "***Invalid",
    "***Undef",
    "'",
    "-NONE-",
    "Keymap Editor",
    "Internal",
    "Can't open requested KeyMap\nUsing the default one",
    "You must keep a Prefs key\nFallback to Internal Keymap",
    "Select a KeyMap file",
    "Can't open requested KeyMap",
    "***Internal error!",
    "Save KeyMap to file",
    "File exists, overwrite?",
    "You must keep a Prefs key\nMoved to F10",
    "Can't open file",
    "NoName",
    "Cannot open D64 again",
    "Pressed key:",
    "***Missing",
    "Blank screen",
    "Invalid mode",
    "Normal-TXT INV",
    "MultiCol-TXT",
    "Normal-GFX",
    "MultiCol-GFX",
    "ExtCol-TXT",
    "Normal-TXT 256",
    "User blanked",
    "cp4 Request",
    "cp4 Warning",
    "cp4 Error",
    "Driver Message",
    "cp4 Info",
    "Ok|Cancel",
    "Reading directory...",
    "O",
    "Save Prog",
    "SetMap...",
    "About",
    "?",
    "Sound",
    "Speed Limit",
    "L",
    "TwoFrame",
    "2",
    "J",
    "Display Percent",
    "IEC",
    "RealTime",
    "SID",
    "D",
    "ScreenMode",
    "On Screen Display",
    "KeyMap",
    "Use",
    "ChunkyToPlanar",
    "Preferences",
    "cp4 Preferences",
    "Can't Create Pattern",
    "Can't Find c2p Directory, /c2p",
    "No memory for read directory",
    "by",
    "Select a ScreenMode",
    "Select a C+4 file",
    "Save program",
    "No file loaded",
    "Can't initialize KeyMapEditor",
    "C= Plus4 Emulator\nWritten by Gáti Gergely (gega)\nE-Mail: gatig@dragon.klte.hu\nWWW: www.klte.hu/~gatig/cp4.html",
    "Invalid DisplayID",
    "No c2p Presents",
    "Can't Initialize SID",
    "Can't Allocate Audio",
    "Can't Open iec.library",
    "Can't Open New Screen",
    "Can't Open Screen",
    "Invalid Size",
    "Text Size",
    "Graphics Size",
    "Extreme Size",
    "Maximum Size",
    "Fatal Error in Prefs",
    "NULL option added",
    "Out of memory",
    "Invalid line",
    "Wrong filetype of KeyMap",
    "Can't Allocate Gameport/Joystick\nTrying again",
    "Can't Allocate Gameport/Joystick",
    "Can't Free gameport.device",
    "cp4 Plus/4 Emulator",
    "Too long Driver Message",
    "Can't initialize user selected c2p\nFallback to default driver",
    "Can't create ColorTable",
    "Can't create BackTable",
    "Can't open requested KeyMap\nUsing default KeyMap",
    "Can't open graphics",
    "Can't open gadtools",
    "Can't open asl",
    "Can't Allocate ScreenMode Requester",
    "You must specify a screenmode",
    "Can't create MsgPort",
    "Can't create IORequest",
    "Can't open timer.device",
    "Can't init display",
    "Can't allocate File Requester",
    "Error in Video Driver",
    "Error at New Environment of Driver",
    "Add",
    "S",
    "R",
    "W",
    "M",
    "P",
    "I",
    "Debug",
    "Debug",
    "N",
    "Wrong filetype of D64",
    "Can't open D64 file",
    "Drive",
    "D64",
    "Real 1541",
    "None",
    "Select a D64 file",
    "Make snapshot",
    "Q",
    "Restore snapshot",
    "Y",
    "Not a snapshot file",
    "Snapshot",
    "Restore",
    "Palette",
    "A",
    "Select a palette file",
    "Unknown snapshot subtype",
    "Can't open xpkmaster.library",
    "Checksum error",
    "Xpk",
    "On",
    "X",
    "Fast",
    "Medium",
    "Best",
    NULL
};
